# -*- coding: utf-8 -*-
"""TeamAssignmentW8

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FNmdLIp9SsQKM9aUHJEHOaCJ7-lddU91
"""


import tensorflow as tf
from tensorflow.keras.applications import MobileNetV2
from tensorflow.keras.layers import Dense, Dropout, BatchNormalization, GlobalAveragePooling2D
from tensorflow.keras.models import Sequential
import keras_tuner as kt

# PERSIAPAN DATASET
# Menggunakan dataset CIFAR-10 bawaan
(x_train, y_train), (x_val, y_val) = tf.keras.datasets.cifar10.load_data()

# Preprocessing standar untuk MobileNetV2 (merubah piksel ke rentang yang sesuai)
x_train = tf.keras.applications.mobilenet_v2.preprocess_input(x_train.astype('float32'))
x_val = tf.keras.applications.mobilenet_v2.preprocess_input(x_val.astype('float32'))

# MEMBANGUN ARSITEKTUR & FITUR OPTIMASI
def build_model(hp):
    # Menggunakan Transfer Learning (MobileNetV2)
    # Sesuaikan input_shape dengan dimensi gambar
    base_model = MobileNetV2(input_shape=(32, 32, 3), include_top=False, weights='imagenet')

    # Freeze layer dasar agar tidak merusak weight pre-trained saat awal training
    base_model.trainable = False

    model = Sequential()
    model.add(base_model)
    model.add(GlobalAveragePooling2D())

    # Batch Normalization
    model.add(BatchNormalization())

    # Hyperparameter Tuning 1 --> Jumlah unit pada Dense Layer
    hp_units = hp.Int('dense_units', min_value=64, max_value=256, step=64)
    model.add(Dense(units=hp_units, activation='relu'))

    # Menambahkan Dropout & Hyperparameter Tuning 2 --> Nilai Dropout Rate
    hp_dropout = hp.Float('dropout_rate', min_value=0.2, max_value=0.5, step=0.1)
    model.add(Dropout(rate=hp_dropout))

    # Layer Output
    model.add(Dense(10, activation='softmax'))

    # Hyperparameter Tuning 3 --> Learning Rate untuk Optimizer
    hp_learning_rate = hp.Choice('learning_rate', values=[1e-2, 1e-3, 1e-4])

    model.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=hp_learning_rate),
                  loss='sparse_categorical_crossentropy',
                  metrics=['accuracy'])

    return model

# PROSES HYPERPARAMETER TUNING
# Menggunakan algoritma Hyperband untuk mencari parameter terbaik
tuner = kt.Hyperband(build_model,
                     objective='val_accuracy',
                     max_epochs=10,
                     factor=3,
                     directory='tuning_dir',
                     project_name='optimasi_cnn_tugas2')

print("Starting process Hyperparameter Tuning...")
tuner.search(x_train, y_train, epochs=10, validation_data=(x_val, y_val))

# Mengambil kombinasi parameter terbaik
best_hps = tuner.get_best_hyperparameters(num_trials=1)[0]
print(f"""
Search finished! Best parameter found:
- Dense Units: {best_hps.get('dense_units')}
- Dropout Rate: {best_hps.get('dropout_rate')}
- Learning Rate: {best_hps.get('learning_rate')}
""")

# TRAINING MODEL MATANG
print("Training final model using best hyperparameter...")
# Membangun ulang model dengan parameter terbaik
model_final = tuner.hypermodel.build(best_hps)

# Melatih model
history = model_final.fit(x_train, y_train, epochs=15, validation_data=(x_val, y_val))

# MENYIMPAN MODEL
# Simpan model yang sudah ditraining
file_name = 'cnn_model_optimized.keras'
model_final.save(file_name)
print(f"Succeed! Model saved with name '{file_name}'")

loss, accuracy = model_final.evaluate(x_val, y_val)

print(f"Validation Accuracy : {accuracy:.4f}")